### ISSUE TITLE
Error: Invalid value specified for positional arg.

### ISSUE THREAD

**Issue by tnorthcutt** [runcommand/dist-archive#4]
When in `/wp-content`, running `wp dist-archive ./plugin-dir-name --format=zip --debug` results in:

```
Debug: No readable global config found (0.009s)
Debug: No project config found (0.01s)
Debug: Loading packages from: /Users/travis/.wp-cli/packages/vendor/autoload.php (0.01s)
Debug: ABSPATH defined: /Users/travis/Sites/sitename/ (0.014s)
Debug: Running command: dist-archive (0.014s)
Error: Invalid value specified for positional arg.
```
Happy to debug, just not sure how yet. I did notice there was a [recent commit to wp-cli](https://github.com/wp-cli/wp-cli/commit/dcae93f329695074623fdb67b24c4b88d49bbcca) dealing with positional arguments - perhaps that's a clue?

Regardless, I've confirmed that it's failing [here](https://github.com/wp-cli/wp-cli/blob/81a463134285025a01dfc14b306176f103f7ab3c/php/WP_CLI/Dispatcher/Subcommand.php#L283), if that helps.

**Comment by danielbachhuber** [comment]
Hm, I can't reproduce:

```
$ wp dist-archive evergreen-content-highlighter
Success: Created evergreen-content-highlighter.0.2.0-alpha.zip
$ wp dist-archive ./evergreen-content-highlighter
Success: Created evergreen-content-highlighter.0.2.0-alpha.zip
$ wp dist-archive ./evergreen-content-highlighter --format=zip
Success: Created evergreen-content-highlighter.0.2.0-alpha.zip
```

Can you share your full command execution?

**Comment by tnorthcutt** [comment]
Crap, sorry @danielbachhuber. I wrote this issue up, then tracked it down to not being on `0.24.0`, and thought I hadn't submitted the issue yet. My apologies for the waste of time!


_Though on reflection, perhaps building a version compatibility check system in core would be beneficial? I may be able to help with that if you deem it useful._

**Comment by danielbachhuber** [comment]
> Though on reflection, perhaps building a version compatibility check system in core would be beneficial? I may be able to help with that if you deem it useful.

Yep! See https://github.com/wp-cli/wp-cli/issues/2675
